./neo4j-admin import \
    --id-type=STRING \
    --skip-duplicate-nodes=true \
    --ignore-empty-strings=true \
    --nodes=import/company.csv \
    --nodes=import/concept.csv \
    --nodes=import/holder.csv \
    --nodes=import/manager.csv \
    --relationships=import/company_concept.csv \
    --relationships=import/holder_company.csv \
    --relationships=import/manager_company.csv